name: Workflow ejercicio 1

on: push

jobs:
  cartera:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Instala pytest
        run: pip install pytest
      - name: Probar test
        run: pytest test.py
